# Generated by Django 4.2.7 on 2023-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('debut', models.IntegerField()),
                ('ciudad_de_origen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('duracion', models.IntegerField()),
                ('genero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('duracion', models.IntegerField()),
                ('generos', models.IntegerField()),
                ('formato', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('image', models.ImageField(upload_to='disco_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio_de_grabacion', models.CharField(max_length=50)),
            ],
        ),
    ]
